//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel;
using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ActorDatabase {
    
    private ActorDatabaseDefinition[] definitionField;
    
    private string programVersionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Definition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ActorDatabaseDefinition[] Definition {
        get {
            return this.definitionField;
        }
        set {
            this.definitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ProgramVersion {
        get {
            return this.programVersionField;
        }
        set {
            this.programVersionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActorDatabaseDefinition {
    
    private ActorDatabaseDefinitionItem[] itemField;
    
    private string isDefaultField;
    
    private string numberField;
    
    private string displayModelField;
    
    private string pickModelField;
    
    private string frontOffsetField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [CategoryAttribute("Definition")]
    public ActorDatabaseDefinitionItem[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IsDefault {
        get {
            return this.isDefaultField;
        }
        set {
            this.isDefaultField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [CategoryAttribute("Actor Description")]
    public string Number {
        get {
            return this.numberField;
        }
        set {
            this.numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DisplayModel {
        get {
            return this.displayModelField;
        }
        set {
            this.displayModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PickModel {
        get {
            return this.pickModelField;
        }
        set {
            this.pickModelField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FrontOffset {
        get {
            return this.frontOffsetField;
        }
        set {
            this.frontOffsetField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActorDatabaseDefinitionItem {
    
    private ActorDatabaseDefinitionItemOption[] optionField;
    
    private string indexField;
    
    private string valueTypeField;
    
    private string displayStyleField;
    
    private string usageField;
    
    private string descriptionField;
    
    private string controlTypeField;
    
    private string maskField;
    
    /// <remarks/>
    [EditorAttribute(typeof(XmlActorBuilder.ItemOptionsEditor), typeof(System.Drawing.Design.UITypeEditor))]
    [System.Xml.Serialization.XmlElementAttribute("Option", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ActorDatabaseDefinitionItemOption[] Option {
        get {
            return this.optionField;
        }
        set {
            this.optionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Index {
        get {
            return this.indexField;
        }
        set {
            this.indexField = value;
        }
    }

    /// <remarks/>
    [TypeConverter(typeof(ValueTypeConverter))]
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ValueType {
        get {
            return this.valueTypeField;
        }
        set {
            this.valueTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DisplayStyle {
        get {
            return this.displayStyleField;
        }
        set {
            this.displayStyleField = value;
        }
    }

    /// <remarks/>
    [TypeConverter(typeof(UsageTypeConverter))]
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Usage {
        get {
            return this.usageField;
        }
        set {
            this.usageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }

    /// <remarks/>
    [TypeConverter(typeof(ControlTypeConverter))]
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ControlType {
        get {
            return this.controlTypeField;
        }
        set {
            this.controlTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Mask {
        get {
            return this.maskField;
        }
        set {
            this.maskField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ActorDatabaseDefinitionItemOption {
    
    private string valueField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private ActorDatabase[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ActorDatabase")]
    public ActorDatabase[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
