using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Atom.RSP
{
    class opcodes_priv_h
    {
        public static Dictionary<opcodes, uint> OpcodeFlags = new Dictionary<opcodes, uint>();
        static opcodes_priv_h()
        {
            BuildRspOps();
        }
        private static void RSP_BUILD_OP(opcodes o, uint f)
        {
            OpcodeFlags.Add(o, f);
        }
        private static uint INFO(params OPCODE_INFO[] args)
        {
            uint result = 0;
            foreach (var item in args)
                result |= (uint)item;
            return result;
        }
        private static void BuildRspOps()
        {
            RSP_BUILD_OP(opcodes.INVALID, INFO(OPCODE_INFO.NONE));
            //RSP_BUILD_OP(opcodes.VINVALID, INFO(OPCODE_INFO.VECTOR));

            RSP_BUILD_OP(opcodes.ADDIU, INFO(OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.ADDU, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.AND, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.ANDI, INFO(OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.BEQ, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.BGEZ, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.BGEZAL, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.BGTZ, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.BLEZ, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.BLTZ, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.BLTZAL, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.BNE, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.BREAK, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.J, INFO(OPCODE_INFO.BRANCH));
            RSP_BUILD_OP(opcodes.JAL, INFO(OPCODE_INFO.BRANCH));
            RSP_BUILD_OP(opcodes.JALR, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.JR, INFO(OPCODE_INFO.BRANCH, OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.LB, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LBU, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LH, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LHU, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LUI, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.LW, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.NOP, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.NOR, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.OR, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.ORI, INFO(OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.SB, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SH, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SLL, INFO(OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SLLV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SLT, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SLTI, INFO(OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.SLTIU, INFO(OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.SLTU, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SRA, INFO(OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SRAV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SRL, INFO(OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SRLV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.SUBU, INFO(OPCODE_INFO.NEEDRS));
            RSP_BUILD_OP(opcodes.SW, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.XOR, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.XORI, INFO(OPCODE_INFO.NEEDRS));

            RSP_BUILD_OP(opcodes.MFC0, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.MTC0, INFO(OPCODE_INFO.NEEDRT));

            RSP_BUILD_OP(opcodes.CFC2, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.CTC2, INFO(OPCODE_INFO.NEEDRT));
            RSP_BUILD_OP(opcodes.MFC2, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.MTC2, INFO(OPCODE_INFO.NEEDRT));

            RSP_BUILD_OP(opcodes.VABS, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VADD, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VADDC, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VAND, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VCH, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VCL, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VCR, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VEQ, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VGE, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VLT, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VINVALID, INFO(OPCODE_INFO.VECTOR));
            RSP_BUILD_OP(opcodes.VMACF, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMACQ, INFO(OPCODE_INFO.VECTOR));
            RSP_BUILD_OP(opcodes.VMACU, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMADH, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMADL, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMADM, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMADN, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMOV, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMRG, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMUDH, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMUDL, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMUDM, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMUDN, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMULF, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VMULQ, INFO(OPCODE_INFO.VECTOR));
            RSP_BUILD_OP(opcodes.VMULU, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VNAND, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VNE, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VNOP, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS));
            RSP_BUILD_OP(opcodes.VNOR, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VNULL, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS));
            RSP_BUILD_OP(opcodes.VNXOR, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VOR, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VRCP, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VRCPH, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VRCPL, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VRNDN, INFO(OPCODE_INFO.VECTOR));
            RSP_BUILD_OP(opcodes.VRNDP, INFO(OPCODE_INFO.VECTOR));
            RSP_BUILD_OP(opcodes.VRSQ, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VRSQH, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VRSQL, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VSAR, INFO(OPCODE_INFO.VECTOR));
            RSP_BUILD_OP(opcodes.VSUB, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VSUBC, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));
            RSP_BUILD_OP(opcodes.VXOR, INFO(OPCODE_INFO.VECTOR, OPCODE_INFO.NEEDVS, OPCODE_INFO.NEEDVT));

            RSP_BUILD_OP(opcodes.LBV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LDV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LFV, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.LHV, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.LLV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LPV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LQV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LRV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LSV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));
            RSP_BUILD_OP(opcodes.LTV, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.LUV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.LOAD));

            RSP_BUILD_OP(opcodes.SBV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SDV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SFV, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.SHV, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.SLV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SPV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SQV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SRV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SSV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.STV, INFO(OPCODE_INFO.NONE));
            RSP_BUILD_OP(opcodes.SUV, INFO(OPCODE_INFO.NEEDRS, OPCODE_INFO.NEEDVT, OPCODE_INFO.STORE));
            RSP_BUILD_OP(opcodes.SWV, INFO(OPCODE_INFO.NONE));

        }
    }
}
