namespace mzxrules.OcaLib
{
    partial class ORom : Rom
    {
        public enum FileList
        {
            invalid,
            makerom,
            boot,
            dmadata,
            Audiobank,
            Audioseq,
            Audiotable,
            link_animetion,
            icon_item_static,
            icon_item_24_static,
            icon_item_field_static,
            icon_item_dungeon_static,
            icon_item_gameover_static,
            icon_item_jpn_static,
            icon_item_nes_static,
            icon_item_ger_static,
            icon_item_fra_static,
            item_name_static,
            map_name_static,
            do_action_static,
            message_static,
            message_texture_static,
            jpn_font_static,
            nes_font_static,
            jpn_message_data_static,
            nes_message_data_static,
            ger_message_data_static,
            fra_message_data_static,
            staff_message_data_static,
            map_grand_static,
            map_48x85_static,
            map_i_static,
            code,
        }
    }

    partial class MRom : Rom
    {
        public enum FileList
        {
            invalid,
            makerom,
            boot,
            dmadata,
            Audiobank,
            Audioseq,
            Audiotable,
            link_animetion,
            icon_item_static,
            icon_item_24_static,
            icon_item_field_static,
            icon_item_dungeon_static,
            icon_item_gameover_static,
            icon_item_jpn_static,
            icon_item_nes_static,
            icon_item_ger_static,
            icon_item_fra_static,
            item_name_static,
            map_name_static,
            do_action_static,
            message_static,
            message_texture_static,
            jpn_font_static,
            nes_font_static,
            jpn_message_data_static,
            nes_message_data_static,
            ger_message_data_static,
            fra_message_data_static,
            spa_message_data_static,
            staff_message_data_static,
            map_grand_static,
            map_48x85_static,
            map_i_static,
            code,
        }
    }
}
