namespace mzxrules.XActor.MActors
{
    class MSimpleActor : MActorRecord
    {
        public MSimpleActor(short[] record)
            : base(record)
        {
            //"??? (unlisted)"
        }
        protected override string GetActorName()
        {
            if (Actor <= 0x2B1)
                return ActorName[Actor];
            return "out of range";
        }

        #region ActorName
        string[] ActorName = new string[]
        {
            "Player",
            "En_Test",
            "En_GirlA",
            "En_Part",
            "Flames of Various Colours",
            "Wooden Door",
            "Treasure Chest",
            "Gekko & Snapper Miniboss - Gekko",
            "Octorok",
            "Bomb",
            "Wallmaster",
            "Dodongo",
            "Keese",
            "Epona - Cutscenes",
            "Collectable Items",
            "Small Orange Flame That Fades Away",
            "Tatl",
            "Cucco",
            "Tektite",
            "INVALID",
            "Peahat",
            "En_Butte",
            "Bug",
            "Fish",
            "Black Room Transition Plane",
            "Dinolfos",
            "Red Flag on Post",
            "Child Zelda",
            "En_Viewer",
            "Shabom",
            "Studded Lifting Door",
            "INVALID",
            "Zora Fin Returning",
            "Elegy of Emptiness Statues",
            "Frog",
            "INVALID",
            "Skulltula",
            "INVALID",
            "Directional Sign",
            "Obj_Wturn",
            "En_River_Sound",
            "INVALID",
            "En_Ossan",
            "INVALID",
            "INVALID",
            "Death Armos",
            "INVALID",
            "Bombflower",
            "INVALID",
            "INVALID",
            "Armos",
            "Deku Baba",
            "En_M_Fire1",
            "En_M_Thunder",
            "Bg_Breakwall",
            "INVALID",
            "Blue Warp",
            "Torch Stand",
            "Heart Container",
            "Mad Scrub",
            "Red Bubble",
            "Hookshot",
            "Blue Bubble",
            "Fountain Water",
            "INVALID",
            "Termina Field Tree",
            "INVALID",
            "Gomess",
            "Bats Surrounding Gomess?",
            "INVALID",
            "INVALID",
            "Beamos",
            "Demo_Effect",
            "Demo_Kankyo",
            "Floormaster",
            "INVALID",
            "Redead & Gibdo",
            "Stone Tower Temple - Grey Square Stone Elevator",
            "Golden Gauntlets Rock (JP 1.0 Only)",
            "Obj_Mure",
            "Skullwalltula",
            "Object_Kankyo",
            "INVALID",
            "INVALID",
            "Child Epona",
            "Hole in Ground Exit",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "En_Encount1",
            "Light Radiating From Treasure Chest",
            "INVALID",
            "INVALID",
            "Astral Observatory - Majora's Mask Balloon",
            "Rock With Beam of Light",
            "Twisting Path to Clocktower",
            "Mirror Shield Face & Light Ray",
            "INVALID",
            "Shellblade",
            "Mad Jelly",
            "Wilted Deku Baba",
            "Gorman Bros.",
            "INVALID",
            "Ruto",
            "Bombchu",
            "Arrow, Posts, & Splatter",
            "Like Like",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "En_Fr",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "Fishing Pond Owner (JP 1.0 Only)",
            "Pushable Block",
            "Eff_Dust",
            "Bg_Umajump",
            "Fire Arrow",
            "Ice Arrow",
            "Light Arrow",
            "Item_Etcetera",
            "Small Wooden Crate",
            "Pot",
            "INVALID",
            "Iron Knuckle",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "Demo_Shd",
            "Deku Palace - King's Chamber Deku Guard",
            "Tatl Message Prompt",
            "En_Honotrap",
            "En_Tubo_Trap",
            "Obj_Ice_Poly",
            "Freezard",
            "Grass",
            "Floating Bean Plant",
            "Bombable Rock",
            "Obj_Switch",
            "INVALID",
            "Dampé's Grave - Brown Elevator ???",
            "Stone Hookshot Target Pillar",
            "En_Okarina_Tag",
            "INVALID",
            "Grey Boulder That Rolls Around ???",
            "INVALID",
            "INVALID",
            "Carpenter",
            "Cucco Chick",
            "Item_Inbox",
            "Gerudo Lieutenant",
            "Obj_Blockstop",
            "Dynamic Shadow",
            "Dissipating Cloud of Black Smoke Following Explosion",
            "INVALID",
            "Gorman",
            "Bean Seller",
            "Grog",
            "Swamp - Tour Boat",
            "Square Signpost",
            "INVALID",
            "Attacking Cucco",
            "INVALID",
            "INVALID",
            "INVALID",
            "Marine Researcher",
            "Kaepora Gaebora",
            "Rock",
            "Flower With Glitched Te",
            "Sun Switch",
            "Groups of Grass & Rocks",
            "INVALID",
            "Honey & Darling",
            "INVALID",
            "INVALID",
            "Water Spout",
            "En_Mm",
            "INVALID",
            "INVALID",
            "En_Weather_Tag",
            "Part-Timer",
            "INVALID",
            "Moon Child",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "Song of Storms Effect",
            "Title Logo",
            "Green Tatl Z-Target Message",
            "Stone Tower Temple - Floating Stone Platform",
            "INVALID",
            "INVALID",
            "Scarecrow",
            "Obj_Makeoshihiki",
            "Sun's Song Effect",
            "INVALID",
            "En_Torch",
            "INVALID",
            "Shot_Sun",
            "INVALID",
            "INVALID",
            "Obj_Roomtimer",
            "Cursed Man",
            "INVALID",
            "Zelda's Lullaby Effect",
            "Oceff_Storm",
            "Obj_Demo",
            "Mad Jelly - Jelly Droplets?",
            "Deku Nut Projectile",
            "INVALID",
            "INVALID",
            "INVALID",
            "INVALID",
            "Epona's Song Effect",
            "Saria's Song Effect",
            "INVALID",
            "Dog",
            "Gold Skulltula Token",
            "Honeycomb",
            "Normal Wooden Crate",
            "INVALID",
            "Blue Target Spot",
            "Obj_Mure3",
            "Honey & Darling",
            "INVALID",
            "INVALID",
            "Wolfos",
            "Stalchild",
            "INVALID",
            "Gossip Stone",
            "Termina Field - Fountain Sound Effects",
            "Guay",
            "INVALID",
            "Cow",
            "INVALID",
            "INVALID",
            "Scarecrow's Song Effect",
            "INVALID",
            "Zora",
            "Obj_Makekinsuta",
            "Aveil",
            "INVALID",
            "Obj_Hamishi",
            "Skullkid With Flute, OoT, Link Mask, Majora's Mask",
            "Postman's Letter to Himself",
            "INVALID",
            "Door_Spiral",
            "INVALID",
            "Obj_Pzlblock",
            "Blade Trap",
            "INVALID",
            "Armos Statue",
            "Green Bumper",
            "INVALID",
            "INVALID",
            "Dragonfly",
            "INVALID",
            "Obj_Grass",
            "Obj_Grass_Carry",
            "Obj_Grass_Unit",
            "INVALID",
            "INVALID",
            "Bg_Fire_Wall",
            "En_Bu",
            "Circle of Light",
            "Garo Master",
            "Row of Blocks That Collapse on Approach",
            "Igos du Ikana",
            "En_Warp_tag",
            "Mamamu Yan",
            "En_Boj_01",
            "En_Boj_02",
            "En_Boj_03",
            "En_Encount4",
            "Bomber",
            "Swamp Shooting Gallery Manager",
            "INVALID",
            "Blue Icicle",
            "Shooting Gallery - Guay",
            "En_Boj_04",
            "En_Cne_01",
            "En_Bba_01",
            "Shikashi",
            "Spiderweb",
            "INVALID",
            "INVALID",
            "En_Mt_tag",
            "Odolwa",
            "Twinmold",
            "Gyorg",
            "Wart",
            "Bio Deku Baba",
            "Boss_06",
            "Majora",
            "Great Fairy",
            "INVALID",
            "En_Boj_05",
            "INVALID",
            "INVALID",
            "En_Sob1",
            "INVALID",
            "INVALID",
            "Goron",
            "INVALID",
            "Carnivorous Lilypad",
            "Plume of Smoke Rising High Into the Sky",
            "Various Elevators (1, 2, 3, 4, 5)",
            "Woodfall Temple - Wooden Flower",
            "Breakable Pot With Grass",
            "Spike-Covered Log",
            "Cutscene - Boss Remains",
            "Shooting Gallery - Wolfos",
            "Obj_Skateblock",
            "Ice Block That Appears After Freezing Enemy",
            "Gekko & Snapper Miniboss - Snapper",
            "Shooting Gallery - Deku Scrub",
            "Pop Up Tatl Message",
            "Frog",
            "Link Riding Through Lost Woods Cutscene - Tree Trunk",
            "Skullkid With Flute, OoT, Link Mask, Majora's Mask",
            "Chuchu",
            "Desbreko",
            "Clock Tower Spotlight",
            "Chimney E",
            "Stock Pot Inn Bell",
            "Shooting Gallery - Octorok",
            "INVALID",
            "Obj_Shutter",
            "Song of Time Cutscene - Child Zelda",
            "Group of Stray Fairies",
            "Tatl Left Behind Cutscene - Deku Door/Spotlights",
            "Nejiron",
            "Vertically-Oriented Rotating Spiked Log",
            "Romani Ranch - Chimney Smoke Plume",
            "En_Test2",
            "Kafei",
            "Three-Day Timer",
            "Bad Bat",
            "Song of Soaring stone",
            "Wizzrobe",
            "Wizzrobe - Warp Platform",
            "Wizzrobe - Fire Attack",
            "Camera Focuses on Link",
            "Elegy of Emptiness - Beam of Light When Creating Statue",
            "Switch-Deactivated Circle of Flames Surrounding Platforms",
            "Ladder",
            "Black Boe",
            "Demo_Getitem",
            "INVALID",
            "Deku Nut Projectile",
            "Blue Target Spot Saying Koume's Boat Cruise Is Closed",
            "En_Dnk",
            "Deku King",
            "INVALID",
            "Tall Spiked Iron Fence",
            "Boulder Blocking Goron Racetrack",
            "Yellow Target Spot (object_En_Firefly)",
            "Real Bombchu",
            "Water Dripping on Ground",
            "En_Kusa2",
            "Pro",
            "INVALID",
            "Great Bay Temple Gears",
            "En_Dy_E",
            "Tingle With Balloon",
            "Bank Teller",
            "Pirates' Fortress - Telescope on Tripod",
            "Ice Platform That Floats in Water",
            "Deku Palace - Patrolling Deku Guard",
            "En_Mushi2",
            "En_Fall",
            "Counting Game Postman",
            "Strange Wooden/Metal Te",
            "Deku Butler",
            "En_Pr2",
            "Skullfish - Defeated",
            "Garo Master",
            "Pink & Green Deku Flower",
            "Eyegore",
            "Exploding Metal Spike Trap",
            "Related to the water in Woodfall Temple",
            "Koume on Broom",
            "Kotake",
            "INVALID",
            "INVALID",
            "En_Test5",
            "OoT's Night Actor?",
            "Beaver Bros. Big Brother",
            "Rubble Blasted by Eyegore",
            "Snowhead Temple - Central Pillar",
            "Opening Cutscene - Objects",
            "Skullkid With Flute, OoT, Link Mask, Majora's Mask",
            "Tatl?",
            "Woodfall Temple Rises Cutscene - Objects",
            "Clock Tower Roof Cutscene - OoT & Majora's Mask",
            "Cutscene - Happy Mask Salesman",
            "Dm_Char04",
            "Healing Pamela's Father Cutscene - Gibdo Mask",
            "Mountain Village Unfreezes Cutscene - Mountain",
            "Ending Cutscene - Indigo-Go's Milk Bar Stage",
            "Turtle Island Cutscene - Turtle",
            "Beehive Cutscene - Giant Bee",
            "Clock Tower & Light Beam",
            "INVALID",
            "Monkey",
            "Grey Rectangular Stone Block",
            "Deku Palace - Entrance Guard",
            "Snowhead Temple - Bombable Wall",
            "Clock Tower - Swinging Doors",
            "Snowhead Temple - Punchable Central Pole Inserts",
            "Romani",
            "Beaver Dam Twig Te",
            "Romani Ranch - Poe Balloon",
            "En_Door_Etc",
            "Big Octo",
            "Ice Platform Created by Ice Arrow",
            "Elevator With Triforce Texture",
            "En_Time_Tag",
            "Tatl Left Behind Cutscene - Wooden Deku Door",
            "Taunted by Skullkid Cutscene - Spotlights",
            "Honey & Darling's Shop - Rotating Platform",
            "Water Poured Out of Bottle",
            "Stray Fairy",
            "Stray Fairy in Bubble",
            "INVALID",
            "Honey & Darling's Shop - Target",
            "Honey & Darling's Shop - Basket",
            "Happy Mask Salesman",
            "Clock Tower - Rotating Wooden Cog",
            "Kotake on Broom",
            "Door to Top of Clock Tower",
            "Lilypad",
            "Snapper",
            "Treasure Chest Game - Pro",
            "Circle of Water Surrounding Honey & Darling Platform",
            "Business Scrub Carrying Bags",
            "Ivy in Deku Jail",
            "INVALID",
            "Invisible Blue Platforms Seen With Lens of Truth",
            "Treasure Chest Game - Employee",
            "Great Bay - Fisherman",
            "Ocarina of Time - Potion Shop Owner",
            "Curiosity Shop - Owner",
            "Swamp Tourist Center - Guide",
            "INVALID",
            "Clock Town - Gate-Blocking Soldier",
            "Ice Block",
            "Deku Scrub Playground - Employee",
            "Dampé",
            "INVALID",
            "West Clocktown - Stairs",
            "Deku Scrub Playground - Rupee Elevator",
            "Song of Soaring Actor?",
            "Block That Dissolves in Sunlight",
            "Mirror Shield Face & Light Ray",
            "De",
            "Deku Scrub Playground - Large Green Rupee",
            "Bg_Danpei_Movebg",
            "Snow-Covered Tree",
            "Postman Delivering Letters",
            "Termina Field - 2D Song Buttons Appearing on Wall",
            "Elf_Msg4",
            "Elf_Msg5",
            "En_Col_Man",
            "Ikana Well Gibdo",
            "Giant",
            "Large Snowball",
            "Goht",
            "Spirit House - Owner",
            "En_Onpuman",
            "Gate to Goron Shrine",
            "En_Tag_Obj",
            "Dampé's House Facade",
            "Gravestone",
            "Goron Link Switch",
            "INVALID",
            "Eeno",
            "TG_Sw",
            "Poe Sisters",
            "Hiploop",
            "Rocks Kicked Up by Goht",
            "En_Hanabi",
            "Obj_Dowsing",
            "Wind Funnel ???",
            "Racetrack Dog (Arrow Over Head)",
            "Swordsman",
            "Captain Keeta Race - Gatepost",
            "Marine Research Lab Fish",
            "Postbox",
            "Poe",
            "Tent-Shaped Spider Web",
            "Zora Egg",
            "Zubora",
            "Darmani's Ghost",
            "Swordsman's School - Practice Log",
            "Small Snowball",
            "Darmani's Ghost",
            "Darmani's Gravestone",
            "Deku Princess",
            "Biggoron",
            "Goron Hot Spring Water",
            "Gabora",
            "En_Invadepoh",
            "Goron Elder's Son",
            "Anju",
            "INVALID",
            "Giant Bee",
            "Seahorse",
            "Deep Python",
            "Swordsman's School - Gong",
            "Big Poe",
            "Swordsman's School - Cuttable Board",
            "Little Cow Statue Head",
            "Blue Target Spot ???",
            "No Te",
            "Curtain That Lifts to Reveal Flat's Tomb",
            "Ocean Spider House - Bombable Wall",
            "Ocean Spider House - Fireplace Grate",
            "Ocean Spider House - Skullkid Painting",
            "Ocean Spider House - Drawers & Bookshelf",
            "Ikana Graveyard - Circle of Stalchildren",
            "Goron Elder",
            "Koume's Target Game - Koume on Broom",
            "Cremia's Cart",
            "Leever",
            "Milk Bar - Chair",
            "Stone Tower Temple - Rotating Room Pushblock",
            "Stone Tower Temple - Mirror",
            "Stone Tower Temple - Rotating Room",
            "Great Bay Temple - See-Saw",
            "Great Bay Temple - Freezable Geyser",
            "Gerudo Pirate",
            "Patrolling Pirate Guard",
            "Romani",
            "Cremia",
            "South Clock Town - Flags & Carnival Platform",
            "Great Bay Temple - Elevator",
            "Owl Statue",
            "Mikau",
            "Deku Moon Dungeon - Spiked Rotating Platforms",
            "Goron Elder - Drum",
            "Twinmold Arena",
            "Great Bay - Zora With Directions to Zora Hall",
            "North Clock Town - Tree",
            "Elevator?",
            "Pirate's Fortress - Interior Door",
            "Pirate Boat",
            "Wooden Barrel",
            "Switch-Activated Geyser",
            "Koume's Target Game - Target",
            "Mirror Shield Face & Light Ray",
            "Japas",
            "Elf_Msg6",
            "Sakon's Hideout sliding door/conveyor slabs",
            "Toto",
            "Music Box House ???",
            "Bomb Shop Lady",
            "Sakon",
            "Tijo",
            "Clock Town - Lottery Shop",
            "Goron With Don Gero's Mask",
            "Mushroom Scent",
            "Palm Tree",
            "Moths in Woodfall Temple",
            "Bubbles Surrounding Wart?",
            "Fish Surrounding Gyorg?",
            "Goron Village - Chandelier",
            "Evan",
            "Goron Complaining About Baby Crying",
            "Anju's Grandma",
            "Jugglers",
            "Stone Tower Temple - Movable Monkey-Faced Blocks",
            "Elegy of Emptiness Switch",
            "Poe Composers",
            "Guru-Guru",
            "Sonata of Awakening Effect",
            "Shiro",
            "Song of Soaring Effect",
            "Astral Observatory - Business Scrub in Telescope",
            "Astral Observatory - Guay in Telescope",
            "Song of Healing Effect",
            "Wave Created by Turtle Awakening",
            "Pamela's Father",
            "Pamela's Father As a Gibdo",
            "Lulu",
            "Madame Dotour",
            "Music Bo",
            "Stone Tower Temple - Bombable Tan Floor Tile",
            "Stone Tower Temple - Light Rays",
            "Stone Tower Temple - Door",
            "Beneath the Grave - Bombable Wall",
            "Flat's Tomb",
            "Large Rotating Green Rupee",
            "Sharp's Cave",
            "Music Bo",
            "Pamela",
            "Ikana Canyon - Hookshotable Tree",
            "Swamp Spider House - Sleeping Deku Scrub",
            "Great Bay - Zora Complaining About Water",
            "Green Target Spot (Indigo-Go's Poster)",
            "Madame Aroma",
            "Mr. Barten",
            "Bomb Shop Bag Stolen by Sakon",
            "En_Hit_Tag",
            "Guay Circling Clock Town",
            "Flock of Seagulls",
            "En_Tanron5",
            "Flock of Giant Bees",
            "Milk Road - Carpenter Hacking at Boulder",
            "Mutoh",
            "Captain Viscen",
            "En_Heishi",
            "??? - Soldier",
            "Mayor Dotour",
            "Laundry Pool - Sign With Bell",
            "Cremia & Romani's 6pm Dinner",
            "Moon Crashing Into Clocktown Effects",
            "Ikana Castle - Punchable Pillar Segments",
            "Business Scrub",
            "Skullkid Screams to Call Moon Down - Effects",
            "Link the Goron",
            "Medigoron",
            "Captain Keeta",
            "En_Sth2",
            "Kamaro",
            "Rosa Sister",
            "En_Scopecoin",
            "Hand in Toilet",
            "Bombers - Jim",
            "Bombers - Jim",
            "Bombers - Blue-Hatted Bomber",
            "Bombers - Hideout Guard",
            "Bombers - Majora Balloon",
            "Moon's Tear",
            "Obj_Mu_Pict",
            "Various Ikana Objects",
            "Blue Spotlight Effect",
            "Gorman Bros. Buildings",
            "Roof of Cow Barn",
            "Twisted Corpse of Deku Butler's Son",
            "Huge Metal Portcullis",
            "Cart Delivery Bottle of Chateau Romani",
            "Keaton",
            "Astral Observatory - Bombable Wall",
            "Stone Tower Temple - Hot Checkered Ceiling",
            "Captain Keeta",
            "Mayor's Receptionist",
            "Takkuri",
            "Fisherman's Jumping Game - Fisherman",
            "Fisherman's Jumping Game - Torch",
            "Stockpot Inn - 2nd Floor Window",
            "Demo_Syoten",
            "Ending Cutscene - Moon Gets Tossed Back Into Sky",
            "Colourful Hookshot Target Pillar",
            "Link Moon Dungeon - Bombable, Climbable Wall",
            "Anju in Wedding Dress",
            "En_Invadepoh_Demo",
            "Red & Brown Elevator",
            "Falling Moon",
            "Ending Cutscene - Madame Aroma at Wedding",
            "Blue Target Spot",
            "Ending Cutscene - Anju's Mother at Wedding",
            "Ending Cutscene - Anju's Grandmother at Wedding",
            "Wedding Dress Mannequin",
            "Ending Cutscene - Mayor Dotour at Wedding",
            "Ending Cutscene - Tingle at Wedding",
            "Ending Cutscene - Confetti at Wedding",
            "Stalchild - Gives Hints",
            "Dm_Tag",
            "Brown Bird",
            "Ending Cutscene - Vissen at Wedding",
            "Ending Cutscene - Mutoh at Wedding",
            "Ending Cutscene - Soldier Cheering Guruguru",
            "Ending Cutscene - Carpenter Watching Indigo-Go's",
            "En_Ending_Hero6",
            "Blue Target Spot",
            "Obj_Swprize",
            "En_Invisible_Ruppe",
            "Ending Cutscene - Stump With Skullkid's Doodle",
            "Ending Cutscene - Bomb Shop Owner",

        };
        #endregion
    }
}
